default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= Rails.application.credentials.database.database %>
  username: <%= Rails.application.credentials.database.username %>
  password: <%= Rails.application.credentials.database.password %>
  port: 5432
  host: <%= Rails.application.credentials.database.host %>
  pool: 5
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default